[package]
name = "plugins"
version = "0.1.0"
edition = "2021"

[lib]
name = "transactionlogger"
crate-type = ["cdylib"]

[dependencies]
bs58 = "0.5.1"
figment = {version = "0.10.19", features = ["toml", "json", "env"]}
serde = "1.0.228"
agave-geyser-plugin-interface = "3.1.6"
solana-clock = "3.0"
solana-program = "3.0"
solana-sdk = "3.0"
